name: Announce JSON File Changes in Languages Directory with Diff

on:
  push:
    paths:
      - Languages/*.json   # Monitor all .json files in the Languages directory

jobs:
  announce:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Get file diff
        run: |
          DIFF=$(git diff HEAD^ HEAD Languages/*.json | head -c 1900) # Limit diff to 1900 characters for Discord
          DIFF_ESCAPED=$(echo "$DIFF" | sed ':a;N;$!ba;s/\n/\\n/g' | sed 's/"/\\"/g')
          echo "Diff is: $DIFF_ESCAPED"
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"The following changes were made to JSON files in the Languages directory:\n\`\`\`$DIFF_ESCAPED\`\`\`\"}" \
               ${{ secrets.DISCORD_WEBHOOK }}
